server:
  port: 9000
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: first-ek-invoker
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka/
#同样可以通过配置来定义各个属性
#first-ek-provider:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.tzl.cloud.MyRule
#    NFLoadBalancerPingClassName: com.tzl.cloud.MyPing
#    listOfServers: http://localhost:8080,http://localhost:8081